# Generated by Django 4.2.3 on 2023-07-14 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'category_tbl',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'sub_category_tbl',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=100)),
                ('p_category', models.CharField(blank=True, max_length=100)),
                ('p_description', models.TextField(blank=True, max_length=300)),
                ('p_quantity', models.PositiveIntegerField()),
                ('p_price', models.PositiveIntegerField()),
                ('p_image', models.ImageField(blank=True, upload_to='product_img')),
                ('user_id', models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_tbl',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Mbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'product_booking',
            },
        ),
    ]
